### ISSUE TITLE
Brancher l'authentification sur le SSO YunoHost

### ISSUE THREAD

**Issue by JocelynDelalande** [Jojo144/compteur_du_gase_ynh#40]
Une oposition de principe à ce que l'on branche l'authentification du compteur sur celle de yunohost ?

Ça permettrait de gérer l'accès à l'interface d'administration avec des comptes YunoHost. Et ça éviterait que l'on ne demande de choisir encore un mot de passe à l'installation (il suffira alors de demander le nom d'un utilisateur existant dans ynh pour lui attribuer les droits d'admin sur le compteur). Idem pour l'adresse mail.

**Comment by Jojo144** [comment]
Ça serait super !
Faudrait qu'on puisse donner l'accès admin à plusieurs utilisateurs.
